root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  # Build both MCP server and web server for step0
  cmd = "go work sync && cd step0/mcp && go build -o ../../tmp/mcp-server-step0 . && cd ../web && go build -o ../../tmp/web-server-step0 ."
  # Run the web server by default (you can run MCP server separately)
  bin = "./tmp/web-server-step0"
  full_bin = ""
  args_bin = []
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "k6-scripts", ".git"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  # Watch both mcp and web directories in step0
  include_dir = ["step0/mcp", "step0/web"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  # Post build command to show build status
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
