version: '3.8'

services:
  api:
    image: swaggerapi/petstore3:latest
    ports:
      - "8082:8080"
    environment:
      - SWAGGER_HOST=localhost:8080
      - SWAGGER_BASE_PATH=/api/v3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v3/openapi.json"]
      interval: 30s
      timeout: 10s
      retries: 3

  web:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
    depends_on:
      - api